# Choose your own adventure
# Alex Hsiao
# 24 September 2025

import time
print("")
print("")
print("Make the Terminal Tab higher for better experience.")
print('press "Enter" to continue')
pause = input()

print("I realy suggest you make it higher, if you haven't done it.")
print('press "Enter" to continue')
pause = input()

print("Enter your name")
name = input("Name: ")

"""
🟥🟧🟨🟩🟦🟪⬛️⬜️🟫
"""
re = str("🟥")
og = str("🟧")
ye = str("🟨")
gr = str("🟩")
bu = str("🟦")
pu = str("🟪")
bl = str("⬛️")
wh = str("⬜️")
br = str("🟫")

# to test the game faster
if name != str("editor"):
# just some loading animation
    print("loading......")
    time.sleep(0.1)
    print("loading.....")
    time.sleep(0.1)
    print("loading....")
    time.sleep(0.1)
    print("loading...")
    time.sleep(0.1)
    print("loading..")
    time.sleep(0.1)
    print("loading.")
    time.sleep(2)

    # spinning thing
    a = 3
    while a >= 2:
        print("(´･ω･`)")
        time.sleep(0.05)
        print("( ´･ω･)")
        time.sleep(0.05)
        print("(　´･ω)")
        time.sleep(0.05)
        print("( 　´･)")
        time.sleep(0.05)
        print("( 　 ´)")
        time.sleep(0.05)
        print("(     )")
        time.sleep(0.05)
        print("(     )")
        time.sleep(0.05)
        print("(     )")
        time.sleep(0.05)
        print("(`　  )")
        time.sleep(0.05)
        print("(･`   )")
        time.sleep(0.05)
        print("(ω･`　)")
        time.sleep(0.05)
        print("(･ω･` )")
        time.sleep(0.05)
        a = a - 1
        if a == 1:
            print("(´･ω･`)")
    time.sleep(1)
    # game started
    if name != str("noimage"):
        print(wh*38)
        time.sleep(0.02)
        print(wh*8+"⬜️⬜️⬛️⬛️⬜️⬜️⬜️⬛️⬛️⬜️⬜️⬛️⬜️⬜️⬜️⬛️⬜️⬛️⬛️⬛️⬛️⬜️"+wh*8)
        time.sleep(0.02)
        print(wh*8+"⬜️⬛️⬜️⬜️⬜️⬜️⬛️⬜️⬜️⬛️⬜️⬛️⬛️⬜️⬛️⬛️⬜️⬛️⬜️⬜️⬜️⬜️"+wh*8)
        time.sleep(0.02)
        print(wh*8+"⬜️⬛️⬜️⬛️⬛️⬜️⬛️⬜️⬜️⬛️⬜️⬛️⬛️⬛️⬛️⬛️⬜️⬛️⬛️⬛️⬛️⬜️"+wh*8)
        time.sleep(0.02)
        print(wh*8+"⬜️⬛️⬜️⬜️⬛️⬜️⬛️⬛️⬛️⬛️⬜️⬛️⬜️⬛️⬜️⬛️⬜️⬛️⬜️⬜️⬜️⬜️"+wh*8)
        time.sleep(0.02)
        print(wh*8+"⬜️⬜️⬛️⬛️⬜️⬜️⬛️⬜️⬜️⬛️⬜️⬛️⬜️⬜️⬜️⬛️⬜️⬛️⬛️⬛️⬛️⬜️"+wh*8)
        time.sleep(0.02)
        print(wh*38)
        time.sleep(0.02)
        print("⬜️⬜️⬛️⬛️⬛️⬜️⬛️⬛️⬛️⬛️⬛️⬜️⬜️⬛️⬛️⬜️⬜️⬛️⬛️⬛️⬜️⬜️⬛️⬛️⬛️⬛️⬛️⬜️⬛️⬛️⬛️⬛️⬜️⬛️⬛️⬛️⬜️⬜️")
        time.sleep(0.02)
        print("⬜️⬛️⬜️⬜️⬜️⬜️⬜️⬜️⬛️⬜️⬜️⬜️⬛️⬜️⬜️⬛️⬜️⬛️⬜️⬜️⬛️⬜️⬜️⬜️⬛️⬜️⬜️⬜️⬛️⬜️⬜️⬜️⬜️⬛️⬜️⬜️⬛️⬜️")
        time.sleep(0.02)
        print("⬜️⬜️⬛️⬛️⬜️⬜️⬜️⬜️⬛️⬜️⬜️⬜️⬛️⬜️⬜️⬛️⬜️⬛️⬛️⬛️⬜️⬜️⬜️⬜️⬛️⬜️⬜️⬜️⬛️⬛️⬛️⬛️⬜️⬛️⬜️⬜️⬛️⬜️")
        time.sleep(0.02)
        print("⬜️⬜️⬜️⬜️⬛️⬜️⬜️⬜️⬛️⬜️⬜️⬜️⬛️⬛️⬛️⬛️⬜️⬛️⬜️⬛️⬜️⬜️⬜️⬜️⬛️⬜️⬜️⬜️⬛️⬜️⬜️⬜️⬜️⬛️⬜️⬜️⬛️⬜️")
        time.sleep(0.02)
        print("⬜️⬛️⬛️⬛️⬜️⬜️⬜️⬜️⬛️⬜️⬜️⬜️⬛️⬜️⬜️⬛️⬜️⬛️⬜️⬜️⬛️⬜️⬜️⬜️⬛️⬜️⬜️⬜️⬛️⬛️⬛️⬛️⬜️⬛️⬛️⬛️⬜️⬜️")
        time.sleep(0.02)
        print(wh*38)
        time.sleep(2)
    else:
        print("")
        print("[IMAGE ERMOVED]")
        print("")
else:
    time.sleep(1)
    print("")
    print("loading animation skipped")
    time.sleep(1)

# make all image inverted if player name is "jeb_"
if name == ("jeb_"):
    re = str("🟩")
    og = str("🟦")
    ye = str("🟦")
    gr = str("🟥")
    bu = str("🟧")
    pu = str("🟩")
    bl = str("⬜️")
    wh = str("⬛️")
    br = str("🟩")

print("....")
time.sleep(0.5)
print("...")
time.sleep(0.5)
print("..")
time.sleep(0.5)
print(".")
time.sleep(0.5)
print("")
# alarm cloack
print("Today is Sunday you are going to a party later.")
print("")
time.sleep(3)
if name != str("noimage"):
    print(bu*33)
    time.sleep(0.02)
    print(bu*30 + bl*2 + bu)
    time.sleep(0.02)
    print(bu*27 + bl*3 + bu*3)
    time.sleep(0.02)
    print(bu*3 + wh*17 + bu*4 + bl*3 + bu*6)
    time.sleep(0.02)
    print(bu*3 + wh + bl*15 + wh + bu*2 + bl*2 + bu*9)
    time.sleep(0.02)
    print(bu*3 + wh + bl + ye*3 + bl*3 + ye*3 + bl + ye*3 + bl + wh + bu*13)
    time.sleep(0.02)
    print(bu*3 + wh + bl + (ye + bl)*6 + ye + bl + wh + bu*13)
    time.sleep(0.02)
    print(bu*3 + wh + bl + ye*3 + bl*3 + (ye + bl)*3 + ye + bl + wh + bu*13)
    time.sleep(0.02)
    print(bu*3 + wh + bl + (ye + bl)*6 + ye + bl + wh + bu*2 + bl*3 + bu*8)
    time.sleep(0.02)
    print(bu*3 + wh + bl + ye*3 + bl*3 + ye*3 + bl + ye*3 + bl + wh + bu*5 + bl*4 + bu*4)
    time.sleep(0.02)
    print(bu*3 + wh + bl*15 + wh + bu*9 + bl*2 + bu*2)
    time.sleep(0.02)
    print(bu*3 + wh*17 + bu*13)
    time.sleep(0.02)
    print(bu*4 + bl*3 + bu*9 + bl*3 + bu*14)
    time.sleep(0.02)
    print(br*33)
    time.sleep(0.02)
    print(br*33)
else:
    print("[IMAGE ERMOVED]")
print("")
time.sleep(1)
print("Alarm: Bibibi! Bibibi! Bibibi! Bibibi!")
time.sleep(1)
print(f"{name}: AUGHHHHHH!")
time.sleep(1)
print("(You smash the alarm clock)")
time.sleep(3)
print("")
# broken alarm clock
if name != str("noimage"):
    print(bu*33)
    time.sleep(0.02)
    print(bu + bl + bu*7 + bl + bu*15 + bl + bu*7)
    time.sleep(0.02)
    print(bu*9 + bl + bu*13 + bl*2 + bu*8)
    time.sleep(0.02)
    print(bu*3 + wh*2 + bu*5 + bl + bu*7 + wh*2 + bu*2 + bl + bu*10)
    time.sleep(0.02)
    print(bu*2 + wh + bl*2 + wh*2 + bu*7 + wh*4 + bl*2 + wh + bu*12)
    time.sleep(0.02)
    print(bu*2 + wh + bl*4 + wh*2 + bu*2 + wh*3 + bl*6 + wh + bu*12)
    time.sleep(0.02)
    print(bu + wh + bl*2 + ye + bl*4 + wh*2 + bl*6 + ye*2 + bl + wh + bu*12)
    time.sleep(0.02)
    print(bu + wh + bl*2 + ye + bl*7 + (ye + bl*2)*3 + wh + bu*11)
    time.sleep(0.02)
    print(bu + wh + bl*2 + ye*2 + bl + ye + bl*2 + ye*2 + bl*3 + (ye + bl*2)*2 + wh + bu*11)
    time.sleep(0.02)
    print(bu*2 + wh + bl*2 + ye + bl*4 + ye + bl + ye + bl*2 + ye*2 + bl*4 + wh + bu + bl*2 + bu*8)
    time.sleep(0.02)
    print(bu*2 + wh + bl*17 + wh + bu*4 + bl + bu*2 + bl + bu*4)
    time.sleep(0.02)
    print(bu*3 + wh*17 + bu*6 + bl*2 + bu*5)
    time.sleep(0.02)
    print(bu*4 + bl*3 + bu*9 + bl*3 + bu*14)
    time.sleep(0.02)
    print(br*33)
    time.sleep(0.02)
    print(br*33)
else:
    print("[IMAGE ERMOVED]")
print("")
print("!!YOU BROKE THE ALARM CLOCK!!")
print("")
time.sleep(1)
print(f"{name}: Noooo!!")
time.sleep(0.5)
print(f"{name}: I need dat shi to wake up tomorrow!")
time.sleep(2)
print("")
print('(Use number 1 to 9 to select options, and press "Enter" to confirm)')
print("(1) Go out earlier to buy a new alarm clock")
print("(2) Be late tomorrow anyway")
choice_1 = input(": ")

# just in case the player is stupid
while choice_1 != str(1) and choice_1 != str(2):
    print("")
    print("Please choose from the given list")
    print('(Use number 1 to 9 to select the options, and press "Enter" to confirm)')
    choice_1 = input(": ")

# buy alarm clock
if choice_1 == str(1):
    time.sleep(1)
    print("")
    print(f"{name}: Well.")
    time.sleep(1)
    print(f"{name}: I need to go now.")
    time.sleep(1)
    print(f"{name}: Or i'm gonna be late for the party.")
    time.sleep(3)
    print("")
    # bus ontime
    if name != str("noimage"):
        print(bu + bl + wh*29 + bl + bu)
        time.sleep(0.02)
        print(bu + bl + (wh + bl*3)*2 + (wh + bl)*2 + wh*17 + bl + bu)
        time.sleep(0.02)
        print(bu + bl + wh + bl + wh*2 + (wh + bl)*4 + wh*17 + bl + bu)
        time.sleep(0.02)
        print(bu + bl + wh + bl*3 + (wh + bl)*3 + bl*2 + wh*17 + bl + bu)
        time.sleep(0.02)
        print(bu + bl + (wh + bl)*4 + wh*3 + bl + wh*17 + bl + bu)
        time.sleep(0.02)
        print(bu + bl + (wh + bl*3)*2 + wh*3 + bl + wh*17 + bl + bu)
        time.sleep(0.02)
        print(bu + bl + wh*29 + bl + bu)
        time.sleep(0.02)
        print(bu + bl + wh*29 + bl + bu)
        time.sleep(0.02)
        print(bu + bl + wh*29 + bl + bu)
        time.sleep(0.02)
        print(bu + bl + wh*14 + gr + wh*8 + gr + wh*5 + bl + bu)
        time.sleep(0.02)
        print(bu + bl + wh*13 + gr*2 + wh*14 + bl + bu)
        time.sleep(0.02)
        print(bu + bl + wh*14 + gr + wh*2 + gr*2 + wh + gr + wh + (wh + gr)*2 + gr + wh*2 + bl + bu)
        time.sleep(0.02)
        print(gr + bl + wh*14 + gr + wh*2 + (gr + wh)*6 + bl + gr)
        time.sleep(0.02)
        print(gr + bl + wh*13 + gr*2 + (gr + wh)*7 + bl + gr)
        time.sleep(0.02)
        print(gr + bl + wh*29 + bl + gr)
        time.sleep(0.02)
    else:
        print("[IMAGE ERMOVED]")
    print("")
    print("(You walked to the bus stop)")
    time.sleep(1)
    print(f"{name}: Just on time!")
    time.sleep(1)
    print(f"{name}: I don't have to wait too long")
    time.sleep(3)
    print("")
    # bus canceled
    if name != str("noimage"):
        print(bu + bl + wh*29 + bl + bu)
        time.sleep(0.02)
        print(bu + bl + (wh + bl*3)*2 + (wh + bl)*2 + wh*17 + bl + bu)
        time.sleep(0.02)
        print(bu + bl + wh + bl + wh*2 + (wh + bl)*4 + wh*17 + bl + bu)
        time.sleep(0.02)
        print(bu + bl + wh + bl*3 + (wh + bl)*3 + bl*2 + wh*17 + bl + bu)
        time.sleep(0.02)
        print(bu + bl + (wh + bl)*4 + wh*3 + bl + wh*17 + bl + bu)
        time.sleep(0.02)
        print(bu + bl + (wh + bl*3)*2 + wh*3 + bl + wh*17 + bl + bu)
        time.sleep(0.02)
        print(bu + bl + wh*29 + bl + bu)
        time.sleep(0.02)
        print(bu + bl + wh*29 + bl + bu)
        time.sleep(0.02)
        print(bu + bl + wh*29 + bl + bu)
        time.sleep(0.02)
        print(bu + bl + wh*4 + re + (wh + re*2)*2 + wh*3 + (re + wh + re)*2 + wh*2 + (re*2 + wh)*2 + wh + bl + bu)
        time.sleep(0.02)
        print(bu + bl + wh*3 + (re + wh*2)*2 + (re + wh)*2 + (re + wh*2)*4 + (re + wh)*2 + bl + bu)
        time.sleep(0.02)
        print(bu + bl + wh*3 + re + wh*2 + re + (re + wh)*3 + re + (wh*2+ re*2 + wh + re)*2 + wh + re + wh + bl + bu)
        time.sleep(0.02)
        print(gr + bl + wh*3 + (re + wh*2)*2 + (re + wh)*2 + (re + wh*2)*4 + (re + wh)*2 + bl + gr)
        time.sleep(0.02)
        print(gr + bl + wh*3 + (wh + re)*2 + (re + wh)*3 + wh + re + (wh +re*2)*4 + wh*2 + bl + gr)
        time.sleep(0.02)
        print(gr + bl + wh*29 + bl + gr)
        time.sleep(0.02)
    else:
        print("[IMAGE ERMOVED]")
    print("")
    print("!!THE BUS WAS CANCELED!!")
    print("")
    print(f"{name}: $#&%$*^&%&*&^*^$^%$#%#*")
    time.sleep(1)
    print(f"{name}: Wat da hellll?!?!")
    time.sleep(1)
    print(f"{name}: This shi happens every time!")
    time.sleep(1)
    print(f"{name}: AWESOME!!  >:( ")
    time.sleep(1)
    print(f"{name}: Now I'll have to wait for 15 minutes!")
    time.sleep(1)
    print(f"{name}: I could of have have my breakfast!")
    time.sleep(1)

# don't buy alarm clock
if choice_1 == str(2):
    time.sleep(1)
    print("")
    print(f"{name}: The first block tomorrow is not Programming.")
    time.sleep(1)
    print(f"{name}: I won't miss out anything.")
    time.sleep(1)
    print(f"{name}: Since i'm not going ealier, I can have some breakfast.")
    time.sleep(3)
    print("")
    # empty plate
    if name != str("noimage"):
        print(br*33)
        time.sleep(0.02)
        print(br*33)
        time.sleep(0.02)
        print(br*33)
        time.sleep(0.02)
        print(br*12 + wh*9 + br*12)
        time.sleep(0.02)
        print(br*9 + wh*15 + br*9)
        time.sleep(0.02)
        print(br*8 + wh*17 + br*8)
        time.sleep(0.02)
        print(br*7 + wh*19 + br*7)
        time.sleep(0.02)
        print(br*7 + wh*19 + br*7)
        time.sleep(0.02)
        print(br*7 + wh*19 + br*7)
        time.sleep(0.02)
        print(br*8 + wh*17 + br*8)
        time.sleep(0.02)
        print(br*9 + wh*15 + br*9)
        time.sleep(0.02)
        print(br*12 + wh*9 + br*12)
        time.sleep(0.02)
        print(br*33)
        time.sleep(0.02)
        print(br*33)
        time.sleep(0.02)
        print(br*33)
    else:
        print("[IMAGE ERMOVED]")
    print("")
    print(f"{name}: mmmmm...")
    time.sleep(1)
    print(f"{name}: What should I eat?")
    time.sleep(1)
    print(f"{name}: I only have some eggs and breads.")
    time.sleep(3)
    print("")
    # egg and bread
    if name != str("noimage"):
        print(br*33)
        time.sleep(0.02)
        print(br*33)
        time.sleep(0.02)
        print(br*33)
        time.sleep(0.02)
        print(br*12 + wh*9 + br*12)
        time.sleep(0.02)
        print(br*9 + wh*15 + br*9)
        time.sleep(0.02)
        print(br*8 + wh*4 + og*3 + wh*3 + og*4 + wh*3 + br*8)
        time.sleep(0.02)
        print(br*7 + wh*4 + og + wh*3 + og + wh*2 + ye*4 + og + wh*3 + br*7)
        time.sleep(0.02)
        print(br*7 + wh*3 + og + wh*2 + ye*2 + wh + og + wh*2 + ye* 3 + og + wh*3 + br*7)
        time.sleep(0.02)
        print(br*7 + wh*4 + og + wh + ye*2 + wh + og + wh*3 + ye*3 + og + wh*2 + br*7)
        time.sleep(0.02)
        print(br*8 + wh*4 + og + wh*2 + og + wh*5 + ye*2 + og + wh + br*8)
        time.sleep(0.02)
        print(br*9 + wh*4 + og*2 + wh*9 + br*9)
        time.sleep(0.02)
        print(br*12 + wh*9 + br*12)
        time.sleep(0.02)
        print(br*33)
        time.sleep(0.02)
        print(br*33)
        time.sleep(0.02)
        print(br*33)
    else:
        print("[IMAGE ERMOVED]")
    print("")
    print(f"{name}: Then, that's waht i'll eat.")
    time.sleep(1)
    print(f"{name}: mmmmmmmmmmmmmmmm....")
    time.sleep(3)
    print("")
    # finished plate
    if name != str("noimage"):
        print(br*33)
        time.sleep(0.02)
        print(br*33)
        time.sleep(0.02)
        print(br*33)
        time.sleep(0.02)
        print(br*12 + wh*9 + br*12)
        time.sleep(0.02)
        print(br*9 + wh*15 + br*9)
        time.sleep(0.02)
        print(br*8 + wh*9 + og + wh*7 + br*8)
        time.sleep(0.02)
        print(br*7 + wh*5 + ye + wh*2 + ye + wh*5 + og + wh*4 + br*7)
        time.sleep(0.02)
        print(br*7 + wh*4 + ye*3 + wh*12 + br*7)
        time.sleep(0.02)
        print(br*7 + wh*5 + ye*4 + wh*10 + br*7)
        time.sleep(0.02)
        print(br*8 + wh*6 + ye + wh*4 + og + wh*5 + br*8)
        time.sleep(0.02)
        print(br*9 + wh*15 + br*9)
        time.sleep(0.02)
        print(br*12 + wh*9 + br*12)
        time.sleep(0.02)
        print(br*33)
        time.sleep(0.02)
        print(br*33)
        time.sleep(0.02)
        print(br*33)
    else:
        print("[IMAGE ERMOVED]")
    print("")
    print(f"{name}: That was awesome.")
    time.sleep(1)
    print(f"{name}: I think this time to go to the party.")
    time.sleep(1)
    if name != str("noimage"):
        print(bu + bl + wh*29 + bl + bu)
        time.sleep(0.02)
        print(bu + bl + (wh + bl*3)*2 + (wh + bl)*2 + wh*17 + bl + bu)
        time.sleep(0.02)
        print(bu + bl + wh + bl + wh*2 + (wh + bl)*4 + wh*17 + bl + bu)
        time.sleep(0.02)
        print(bu + bl + wh + bl*3 + (wh + bl)*3 + bl*2 + wh*17 + bl + bu)
        time.sleep(0.02)
        print(bu + bl + (wh + bl)*4 + wh*3 + bl + wh*17 + bl + bu)
        time.sleep(0.02)
        print(bu + bl + (wh + bl*3)*2 + wh*3 + bl + wh*17 + bl + bu)
        time.sleep(0.02)
        print(bu + bl + wh*29 + bl + bu)
        time.sleep(0.02)
        print(bu + bl + wh*29 + bl + bu)
        time.sleep(0.02)
        print(bu + bl + wh*29 + bl + bu)
        time.sleep(0.02)
        print(bu + bl + wh*14 + gr + wh*8 + gr + wh*5 + bl + bu)
        time.sleep(0.02)
        print(bu + bl + wh*13 + gr*2 + wh*14 + bl + bu)
        time.sleep(0.02)
        print(bu + bl + wh*14 + gr + wh*2 + gr*2 + wh + gr + wh + (wh + gr)*2 + gr + wh*2 + bl + bu)
        time.sleep(0.02)
        print(gr + bl + wh*14 + gr + wh*2 + (gr + wh)*6 + bl + gr)
        time.sleep(0.02)
        print(gr + bl + wh*13 + gr*2 + (gr + wh)*7 + bl + gr)
        time.sleep(0.02)
        print(gr + bl + wh*29 + bl + gr)
        time.sleep(0.02)
    else:
        print("[IMAGE ERMOVED]")
    print("")
    print("(You walked to the bus stop)")
    time.sleep(1)
    print(f"{name}: Just on time!")
    time.sleep(1)
    print(f"{name}: I don't have to wait too long")
    time.sleep(1)

print("")
print("------------------------------------------------------------")
print("this is it")
print("i havent finish the game")
print("thanks for playing")

# Introduction



# Problem



# Rising Action



# Climax



# Resolution
